# Generated by Django 2.2.2 on 2020-03-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_hospital', models.CharField(max_length=256)),
                ('patient_registration_number', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_contact', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], default='male', max_length=20, null=True)),
                ('patient_address', models.CharField(max_length=256)),
                ('patient_symptoms', models.TextField()),
                ('patient_age', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppoinmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=20)),
                ('patient_contact', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('patient_date', models.DateTimeField()),
                ('patient_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_doctor_name', models.CharField(max_length=50)),
                ('patient_diet', models.TextField()),
                ('patient_progress', models.CharField(max_length=520)),
                ('patient_medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.Medicines')),
                ('patient_registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_s', models.TextField()),
                ('don_t', models.TextField()),
                ('patient_registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.Patient')),
            ],
        ),
    ]
