# Generated by Django 2.2.2 on 2020-03-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_name', models.CharField(max_length=20)),
                ('medical_address', models.CharField(max_length=20)),
                ('online_delivery', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20)),
                ('medical_contact', models.IntegerField()),
                ('medical_email', models.EmailField(max_length=254, unique=True)),
                ('medical_password', models.CharField(max_length=50)),
                ('medicine_file', models.FileField(null=True, upload_to='medical/file')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=256)),
                ('medical_name', models.ManyToManyField(to='medicalapp.Medical')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_image', models.ImageField(upload_to='medical')),
                ('medical_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.Medical')),
            ],
        ),
    ]
