# Generated by Django 2.2.2 on 2020-03-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('DNB', 'DNB'), ('ENT', 'ENT'), ('MS', 'MS'), ('DCH', 'DCH'), ('BAMS', 'BAMS'), ('BDS', 'BDS'), ('BUMS', 'BUMS'), ('BHMS', 'BHMS'), ('BYNS', 'BYMS'), ('BVSc&AH', 'BVSc&AH'), ('BPT', 'BPT')], max_length=20)),
                ('doctor_speciality', models.CharField(choices=[('Optometry', 'Optometry'), ('DM&MCH', 'DM&MCH'), ('BOT', 'BOT'), ('Cardiology', 'Cardiology'), ('Neurosergery', 'Neurosergery'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=50)),
                ('hospital_info', models.TextField()),
                ('hospital_type', models.CharField(choices=[('multi-speciality', 'multispeciality'), ('speciality', 'speciality')], default='multi-speciality', max_length=20)),
                ('goverment_scheme', models.TextField()),
                ('hospital_contact', models.IntegerField()),
                ('hospital_speciality', models.TextField()),
                ('membership_available', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20)),
                ('blood_bank', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20)),
                ('hospital_lab', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20)),
                ('hospital_ambulance', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20)),
                ('hospital_bed', models.IntegerField()),
                ('hospital_icu', models.IntegerField()),
                ('hospital_email', models.EmailField(max_length=254, unique=True)),
                ('hospital_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_image', models.ImageField(null=True, upload_to='hospital')),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_qualification', models.CharField(max_length=20)),
                ('doctor_experience', models.FloatField()),
                ('doctor_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=20)),
                ('doctor_speciality', models.ManyToManyField(to='hospitalapp.DoctorSpeciality')),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='doctorspeciality',
            name='hospital_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Hospital'),
        ),
    ]
