# Generated by Django 2.2.2 on 2020-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('DNB', 'DNB'), ('ENT', 'ENT'), ('MS', 'MS'), ('DCH', 'DCH'), ('BAMS', 'BAMS'), ('BDS', 'BDS'), ('BUMS', 'BUMS'), ('BHMS', 'BHMS'), ('BYNS', 'BYMS'), ('BVSc&AH', 'BVSc&AH'), ('BPT', 'BPT')], max_length=20)),
                ('doctor_experience', models.FloatField()),
                ('doctor_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=20)),
                ('doctor_speciality', models.CharField(choices=[('Optometry', 'Optometry'), ('DM&MCH', 'DM&MCH'), ('BOT', 'BOT'), ('Cardiology', 'Cardiology'), ('Neurosergery', 'Neurosergery'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry')], max_length=1000)),
                ('doctor_contact', models.IntegerField()),
                ('doctor_image', models.ImageField(null=True, upload_to='doctor')),
                ('doctor_info', models.TextField()),
                ('doctor_email', models.EmailField(max_length=254, unique=True)),
                ('doctor_password', models.CharField(max_length=256)),
            ],
        ),
    ]
